# Generated by Django 4.0.6 on 2022-08-24 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Заголовок новости')),
                ('slug', models.SlugField(unique=True)),
                ('brief_description', models.CharField(max_length=400, verbose_name='Краткое содержание новости')),
                ('description', models.TextField(verbose_name='Полное содержание новости')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания новости')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования новости')),
                ('cover_image', models.ImageField(upload_to='news/', verbose_name='Заглавная картинка для новости')),
                ('time_for_reading', models.IntegerField(verbose_name='Время прочтения новости')),
                ('video_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на видео к новости')),
                ('views', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество просмотров')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовать на сайте')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='NewsAdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Картинка для новости')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Дополнительное изображение',
                'verbose_name_plural': 'Дополнительные изображения',
            },
        ),
    ]
