# Generated by Django 4.0.6 on 2022-08-24 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_employee', models.CharField(max_length=200, verbose_name='ФИО')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название статьи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания статьи')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования статьи')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовать на сайте')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Главная картинка для статьи про сотрудника')),
            ],
            options={
                'verbose_name': 'Статью о сотруднике',
                'verbose_name_plural': 'Статьи о сотрудниках',
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер телефона для связи')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта сотрудника')),
                ('email_for_citizens', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта для обращений граждан')),
                ('image', models.ImageField(blank=True, null=True, upload_to='management/', verbose_name='Фотография')),
                ('info_visits', models.CharField(blank=True, help_text='Пример: каждый четверг с 18.00 до 20.00', max_length=200, null=True, verbose_name='Информация о времени приема граждан')),
            ],
            options={
                'verbose_name': 'Руководство',
                'verbose_name_plural': 'Руководство',
            },
        ),
        migrations.CreateModel(
            name='ArticleAdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Дополнительная картинка для статьи о сотруднике')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employeearticle', verbose_name='Статья о сотруднике')),
            ],
            options={
                'verbose_name': 'Дополнительное изображение',
                'verbose_name_plural': 'Дополнительные изображения',
            },
        ),
    ]
