# Generated by Django 4.0.6 on 2022-08-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='description',
        ),
        migrations.AddField(
            model_name='management',
            name='description_1',
            field=models.TextField(blank=True, default='lol', null=True, verbose_name='Биография, абзац 1'),
        ),
        migrations.AddField(
            model_name='management',
            name='description_2',
            field=models.TextField(blank=True, null=True, verbose_name='Биография, абзац 2'),
        ),
        migrations.AddField(
            model_name='management',
            name='description_3',
            field=models.TextField(blank=True, null=True, verbose_name='Биография, абзац 3'),
        ),
        migrations.AddField(
            model_name='management',
            name='description_4',
            field=models.TextField(blank=True, null=True, verbose_name='Биография, абзац 4'),
        ),
    ]
