# Generated by Django 4.0.6 on 2022-08-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_management_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='description_1',
            field=models.TextField(default='lol', verbose_name='Биография, абзац 1'),
        ),
    ]
