# Generated by Django 4.0.6 on 2022-08-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_management_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleadditionalimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Дополнительная картинка для статьи о сотруднике'),
        ),
        migrations.AlterField(
            model_name='management',
            name='info_visits',
            field=models.CharField(blank=True, help_text='Пример: каждый четверг с 18.00 до 20.00', max_length=200, null=True, verbose_name='Информация о времени приема граждан'),
        ),
    ]
