# Generated by Django 4.0.6 on 2022-08-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_management_description_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='description_1',
            field=models.TextField(verbose_name='Биография, абзац 1'),
        ),
    ]
