# Generated by Django 4.0.6 on 2022-08-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_video', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photolibrary',
            options={},
        ),
        migrations.AddField(
            model_name='photolibrary',
            name='title',
            field=models.CharField(blank=True, default='lol', max_length=100, null=True, verbose_name='Подпись фотографии'),
        ),
        migrations.AddField(
            model_name='videolibrary',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Подпись видео'),
        ),
        migrations.AlterField(
            model_name='photolibrary',
            name='image',
            field=models.ImageField(blank=True, upload_to='photo_library/covers', verbose_name='Выберите фотографию'),
        ),
    ]
