# Generated by Django 4.0.6 on 2022-08-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_video', '0002_alter_photolibrary_options_photolibrary_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photocategory',
            options={'verbose_name': 'Раздел фотоальбома', 'verbose_name_plural': 'Разделы фотоальбомов'},
        ),
        migrations.AlterModelOptions(
            name='videocategory',
            options={'verbose_name': 'Раздел видеоальбома', 'verbose_name_plural': 'Разделы видеоальбомов'},
        ),
        migrations.AlterField(
            model_name='photolibrary',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Подпись фотографии'),
        ),
    ]
