# Generated by Django 4.0.6 on 2022-07-28 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Футбольное поле', 'Футбольное поле'), ('Реклама', 'Реклама'), ('Спорт', 'Спорт'), ('Здоровье', 'Здоровье'), ('Организация мероприятий', 'Организация мероприятий'), ('Прочие услуги', 'Прочие услуги')], max_length=40, verbose_name='Категория услуги')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категория услуги',
                'verbose_name_plural': 'Категории услуг',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('slug', models.SlugField(unique=True)),
                ('brief_description', models.CharField(max_length=400, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Полное описание')),
                ('price_with_VAT', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Тариф с НДС')),
                ('price_without_VAT', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Тариф без НДС')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ед.измерения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Изображение')),
                ('publish', models.BooleanField(default=True, verbose_name='Добавить на сайт')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления услуги')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования услуги')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.categoryservice', verbose_name='Категория услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
