# Generated by Django 4.0.6 on 2022-07-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Имя клиента')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('status', models.CharField(choices=[('в обработке', 'в обработке'), ('новая заявка', 'новая заявка'), ('обработана', 'обработана')], default='новая заявка', max_length=20, verbose_name='Статус заявки')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-data'],
            },
        ),
    ]
