# Generated by Django 4.0.6 on 2022-07-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-date'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='data',
            new_name='date',
        ),
    ]
