# Generated by Django 4.0.6 on 2022-07-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_feedback_options_rename_data_feedback_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryservice',
            options={'verbose_name': 'Категорию услуг', 'verbose_name_plural': 'Категории услуг'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-date'], 'verbose_name': 'Заявку', 'verbose_name_plural': 'ЗАЯВКИ ПЕРЕЗВОНИТЬ'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услугу', 'verbose_name_plural': 'Услуги'},
        ),
    ]
