# Generated by Django 4.0.6 on 2022-07-28 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_categoryservice_options_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='publish',
            new_name='published',
        ),
    ]
