# Generated by Django 4.0.6 on 2022-08-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_publish_service_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price_with_VAT',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_without_VAT',
        ),
        migrations.AddField(
            model_name='service',
            name='price_with_VAT_for_legal',
            field=models.CharField(blank=True, default=0, help_text='Можно дописывать, например, "от", "индивидуально" и т.п.', max_length=50, null=True, verbose_name='Тариф с НДС для юр.лица'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_with_VAT_for_person',
            field=models.CharField(blank=True, default=0, help_text='Можно дописывать, например, "от", "индивидуально" и т.п.', max_length=50, null=True, verbose_name='Тариф с НДС для физ.лица'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_without_VAT_for_legal',
            field=models.CharField(blank=True, default=0, help_text='Можно дописывать, например, "от", "индивидуально" и т.п.', max_length=50, null=True, verbose_name='Тариф без НДС для юр.лица'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_without_VAT_for_person',
            field=models.CharField(blank=True, default=0, help_text='Можно дописывать, например, "от", "индивидуально" и т.п.', max_length=50, null=True, verbose_name='Тариф без НДС для физ.лица'),
        ),
    ]
