# Generated by Django 4.0.6 on 2022-08-04 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_service_price_with_vat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/', verbose_name='Файл')),
                ('title', models.CharField(max_length=50, verbose_name='Название файла')),
                ('description', models.CharField(max_length=100, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'Файл для услуги',
                'verbose_name_plural': 'Файлы для услуги',
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.attachment', verbose_name='Прикрепленный файл'),
        ),
    ]
