# Generated by Django 4.0.6 on 2022-08-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_service_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_primary_service',
            field=models.BooleanField(default=False, verbose_name='Главная услуга'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary_service', True)), fields=('is_primary_service',), name='unique_is_primary_service'),
        ),
    ]
