# Generated by Django 4.0.6 on 2022-07-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта клиента')),
            ],
            options={
                'verbose_name': 'Адрес электронной почты',
                'verbose_name_plural': 'Адреса электронной почты',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Номера телефонов, эл. почты, контактные лица', 'verbose_name_plural': 'Номера телефонов, эл. почты, контактные лица'},
        ),
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'verbose_name': 'Ссылки на соцсети', 'verbose_name_plural': 'Ссылки на соцсети'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_ad',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта отдел рекламы'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_reception_1',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта №1 приемная'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_reception_2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта №2 приемная'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='number_phone_ad',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер тел. отдел рекламы'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='number_phone_reception',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер тел. приемной'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='social_Facebook',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на Фейсбук'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='social_Instagram',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на Инстаграм'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='social_TG',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на Телеграм'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='social_VK',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на ВКонтакте'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='social_Youtube',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на YouTube'),
        ),
    ]
