# Generated by Django 4.0.6 on 2022-07-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Номера телефонов, эл.почты, контактных лиц', 'verbose_name_plural': 'Номера телефонов, эл. почты, контактные лица'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Партнера', 'verbose_name_plural': 'Партнеры'},
        ),
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'verbose_name': 'Ссылку на соцсеть', 'verbose_name_plural': 'Ссылки на соцсети'},
        ),
    ]
