# Generated by Django 4.0.6 on 2022-07-28 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contact_options_alter_partner_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentinfo',
            options={'verbose_name': 'Реквизиты для оплаты', 'verbose_name_plural': 'Реквизиты для оплаты'},
        ),
        migrations.AlterModelOptions(
            name='useremail',
            options={'verbose_name': 'Электронную почту клиента', 'verbose_name_plural': 'Электронные почты клиентов'},
        ),
    ]
