# Generated by Django 4.0.6 on 2022-08-04 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_paymentinfo_options_alter_useremail_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, verbose_name='Видео для главной страницы')),
            ],
            options={
                'verbose_name': 'Ссылку на видео',
                'verbose_name_plural': 'Ссылки на видео',
            },
        ),
        migrations.CreateModel(
            name='VideoAdditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на дополнительное видео')),
                ('urls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.video', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Ссылку на видео',
                'verbose_name_plural': 'Ссылки на видео',
            },
        ),
    ]
