# Generated by Django 4.0.6 on 2022-08-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_video_videoadditional'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_person_personnel',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Контактное лицо отдел кадров'),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_personnel',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта отдел кадров'),
        ),
        migrations.AddField(
            model_name='contact',
            name='number_phone_personnel',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер тел. отдел кадров'),
        ),
    ]
