# Generated by Django 4.0.6 on 2022-09-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='Возраст стадиона')),
            ],
            options={
                'verbose_name': 'Возраст стадиона',
                'verbose_name_plural': 'Возраст стадиона',
            },
        ),
        migrations.CreateModel(
            name='HistoryArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок статьи')),
                ('url', models.CharField(max_length=250, verbose_name='Ссылка на статью')),
            ],
            options={
                'verbose_name': 'Ссылку на статью о стадионе',
                'verbose_name_plural': 'Ссылки на статьи о стадионе',
            },
        ),
    ]
