# Generated by Django 4.0.6 on 2022-09-09 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_vacancy', models.CharField(max_length=100, unique=True, verbose_name='Название вакансии')),
                ('salary', models.CharField(max_length=50, verbose_name='Зарплата')),
                ('experience', models.CharField(max_length=50, verbose_name='Опыт работы')),
                ('employment', models.CharField(max_length=50, verbose_name='Занятость')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='VacancyRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например, ТРЕБОВАНИЯ, ОБЯЗАННОСТИ, ПРИВЕТСТВУЕТСЯ, ОПЫТ РАБОТЫ и т.д.', max_length=100, verbose_name='Название требования')),
                ('list_of_requirements', models.TextField(help_text='Скопируйте этот тег в Пункты требования: &lt;li&gt;ВВЕДИТЕ ВАШ ТЕКСТ В ЭТОМ ТЕГЕ&lt;/li&gt;', verbose_name='Пункты требования')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackForVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('resume_file', models.FileField(upload_to='./resumes/', verbose_name='Файл резюме')),
                ('url_of_resume', models.CharField(max_length=250, verbose_name='ссылка на резюме')),
                ('status', models.CharField(choices=[('in_process', 'В обработке'), ('new_request', 'Новая заявка'), ('reject', 'Отклонить'), ('recruit', 'Принять на работу')], default='in_process', max_length=15, verbose_name='Статус заявки')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Отклик на вакансию',
                'verbose_name_plural': 'Отклики на вакансии',
            },
        ),
    ]
