# Generated by Django 4.0.6 on 2022-08-29 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackforvacancy',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='./resumes/', verbose_name='Файл резюме'),
        ),
        migrations.AlterField(
            model_name='feedbackforvacancy',
            name='url_of_resume',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ссылка на резюме'),
        ),
        migrations.AlterField(
            model_name='feedbackforvacancy',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacancies.vacancy', verbose_name='Вакансия'),
        ),
    ]
