# Generated by Django 4.0.6 on 2022-08-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='description',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment',
            field=models.CharField(default='lol', max_length=50, verbose_name='Занятость'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(default='lol', max_length=50, verbose_name='Опыт работы'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(default='lol', max_length=50, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='vacancyrequirements',
            name='title',
            field=models.CharField(help_text='Например, ТРЕБОВАНИЯ, ОБЯЗАННОСТИ, ПРИВЕТСТВУЕТСЯ, ОПЫТ РАБОТЫ и т.д.', max_length=100, verbose_name='Название требования'),
        ),
        migrations.DeleteModel(
            name='MainInformationOfVacancy',
        ),
    ]
