# Generated by Django 4.0.6 on 2022-08-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_remove_vacancy_description_vacancy_employment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='employment',
            field=models.CharField(max_length=50, verbose_name='Занятость'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(max_length=50, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(max_length=50, verbose_name='Зарплата'),
        ),
    ]
