# Generated by Django 4.0.6 on 2022-08-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_feedbackforvacancy_resume_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликовать на сайте'),
        ),
    ]
