# Generated by Django 4.0.6 on 2022-08-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_vacancy_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='title_of_vacancy',
            field=models.CharField(max_length=100, verbose_name='Название вакансии'),
        ),
    ]
