# Generated by Django 4.0.6 on 2022-08-24 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_alter_vacancy_employment_alter_vacancy_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('resume_file', models.FileField(upload_to='./resumes/', verbose_name='Файл резюме')),
                ('url_of_resume', models.CharField(max_length=250, verbose_name='ссылка на резюме')),
                ('status', models.CharField(choices=[('in_process', 'В обработке'), ('new_request', 'Новая заявка'), ('reject', 'Отклонить'), ('recruit', 'Принять на работу')], default='in_process', max_length=15, verbose_name='Статус заявки')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
        ),
    ]
